package utils;

/**
 * @@author A0088646M
 * @author yeehuipoh
 *
 */
public enum Command {
	ADD, DELETE, UPDATE, VIEW, VIEW_ALL, UNDO, UNDELETE, FILTER, STORAGE_LOCATION, PREVIOUS, NEXT, EXIT, HELP, SEARCH, ADD_SUBTASK, VIEW_MONTH, VIEW_HOME, VIEW_DAY, NEXT_DAY, NEXT_MONTH, PREVIOUS_DAY, PREVIOUS_MONTH
}
